### ISSUE TITLE
missing dist directory

### ISSUE THREAD

**Issue by MaxRolinck** [siglesiasg/node-red-hyperledger-fabric-gateway#4]
Thank you for the great work. V1.0.1 is running fine. However, I had struggles with installing latest version 1.0.2. It misses the directory  "dist" and therefore cannot find the respective nodes. Could you please add the "dist" directory again so that the modules listed in package.json can be found and loaded? Thanks!

**Comment by MaxRolinck** [comment]
As an example for my error codes popping up: 
 `fabric-channel : Error: Cannot find module '/home/.../.node-red/node_modules/@siglesiasg/node-red-hyperledger-fabric-gateway/dist/nodes/config/fabric-channel.js'`

**Comment by siglesiasg** [comment]
Hi Max, I think it's fixed, can you check with version 1.0.3?

<img width="561" alt="image" src="https://github.com/siglesiasg/node-red-hyperledger-fabric-gateway/assets/58256317/94b1289f-eea8-401f-9df6-75a0138c230a">

**Comment by MaxRolinck** [comment]
Hi Secundino. Great, thanks for your fast response! It worked now to install the v1.0.3 package without error messages. And the nodes can also be seen in the settings, as on your screenshot. However, the nodes are not listed in the palette. Do you know a reason, why I can't see them and work with them? Restarting node-red and also disabling and enabling the nodes did not help...

**Comment by siglesiasg** [comment]
Got same result as you. I think it's because I've built it using a mac and some links got broken. I've rebuilt it and I got it working in v1.0.4. Could you recheck? Thanks!

![image](https://github.com/siglesiasg/node-red-hyperledger-fabric-gateway/assets/58256317/5ec90c9f-c4e3-4371-b9db-abd57e7c7ce5)

**Comment by MaxRolinck** [comment]
Thank you for your fast support! Now it works.
